### PR TITLE
Fixes possible sub issue with multiple messages

### LINKED ISSUE #17: price streaming crashes occassionally
Hello,

I am testing your great wrapper, it works very nice except from one issue - streaming prices causes a crash occasionally (especially when there are issues with the network). Getting this error message:

```
app_1_49ccf84303d3 |     SyntaxError: Unexpected end of JSON input
app_1_49ccf84303d3 |     at JSON.parse (<anonymous>)
app_1_49ccf84303d3 |     at IncomingMessage.<anonymous> (/botmate/node_modules/simple-fxtrade/dist/node.js:7:31009)
app_1_49ccf84303d3 |     at emitOne (events.js:116:13)
app_1_49ccf84303d3 |     at IncomingMessage.emit (events.js:211:7)
app_1_49ccf84303d3 |     at addChunk (_stream_readable.js:263:12)
app_1_49ccf84303d3 |     at readableAddChunk (_stream_readable.js:250:11)
app_1_49ccf84303d3 |     at IncomingMessage.Readable.push (_stream_readable.js:208:10)
app_1_49ccf84303d3 |     at HTTPParser.parserOnBody (_http_common.js:137:22)
app_1_49ccf84303d3 |     at TLSSocket.socketOnData (_http_client.js:454:20)
app_1_49ccf84303d3 |     at emitOne (events.js:116:13)
```

Disregard the `app_1_49ccf84303d3` part (the application runs in a container). It seems the library is trying to parse incomplete messages some times.

Using node.js `8.14.0`...

### LINKED ISSUE #20: Subscriptions crash due to JSON parsing error
As mentioned in the comments for #17 the Oanda api sends multiple messages on some rare occasions separated by new line. This causes the stream to crash due to JSON parsing error:

```
SyntaxError: Unexpected token { in JSON at position 266
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/lteacher/simple-fxtrade/dist/node.js:7:31422)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at IncomingMessage.Readable.push (_stream_readable.js:197:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
```

The issue happened after running for 6hrs but I think it just takes a while till it happens... dunno but important point is need to handle this.

### PR DESCRIPTION
**Pull request by lteacher**
Fixes #20  by splitting the buffered string data by new line and emitting each message in order.

### CODE REVIEW

File: lib/subscription.coffee [hunk 1]
```diff
@@ -12,14 +12,19 @@ class Subscription extends EventEmitter
...
-
-      @emit 'data', data
+      # It was reported that at times there can be multiple messages in the buffer
+      # somehow, so to be safe the data string is split and processed for each message
+      messages = switch
+        when @options.json
+          data
+            .toString()
+            .split /\r?\n/
+            .filter Boolean
```
Comment (lteacher) [inline lib/subscription.coffee:24]: Note though wouldn't catch more than one space lol... I don't think that is worth covering though yet as this is really for catching stuff like empty array to string etc.

Also there is no check for 'type' anywhere so... not sure what kind of text in the buffer is being streamed that would just have new lines and no valid json... maybe there is some kind of maintenance message or something Oanda are sending back which isnt an error response?
